In [1]:
# imports
import pandas as pd
import numpy as np

In [2]:
# loading in the data

columns = [
    'variance',
    'skewness',
    'curtosis',
    'entropy',
    'label'
]

train_data = pd.read_csv('bank-note/train.csv', names=columns,header=None)
test_data = pd.read_csv('bank-note/test.csv', names=columns, header=None)

train_data

variance  skewness  curtosis  entropy  label
0    3.848100  10.15390  -3.85610 -4.22280      0
1    4.004700   0.45937   1.36210  1.61810      0
2   -0.048008  -1.60370   8.47560  0.75558      0
3   -1.266700   2.81830  -2.42600 -1.88620      1
4    2.203400   5.99470   0.53009  0.84998      0
..        ...       ...       ...      ...    ...
867  0.273310   4.87730  -4.91940 -5.81980      1
868  1.063700   3.69570  -4.15940 -1.93790      1
869 -1.242400  -1.71750  -0.52553 -0.21036      1
870  1.837300   6.12920   0.84027  0.55257      0
871 -2.014900   3.68740  -1.93850 -3.89180      1

[872 rows x 5 columns]

In [3]:
# need to change the labels from [-1,1]
train_data.iloc[:, -1].replace(0, -1, inplace=True)
test_data.iloc[:, -1].replace(0, -1, inplace=True)

# Update the labels in your numpy arrays as well
#train_labels = train_data.iloc[:, -1].values
#test_labels = test_data.iloc[:, -1].values

In [4]:
# now need to split the data to features (columns) and labels (prediction)

x_train = train_data.drop('label', axis=1).values
y_train = train_data['label'].values

x_test = test_data.drop('label', axis=1).values
y_test = test_data['label'].values


In [5]:

y_train

array([-1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1,
        1,  1,  1, -1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,
        1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1,
        1,  1, -1, -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,
        1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1,  1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1,
        1, -1,  1, -1, -1

# 2A

In [11]:
#making a zero weight vector with the number of features
weights = np.zeros(x_train.shape[1])

bias = 0.0

In [12]:
# standard Perceptron most basic single layered nerual network
epochs = 10
#def Perceptron(epochs, x, y)
for epoch in range(epochs):
    #now loop through each training  example
    #use zip to process two examples at once
    for feature, label in zip(x_train, y_train):
        #predict
        predict = np.dot(weights, feature) + bias
        label_predict = np.sign(predict)
        #now see if it is correct, and update if false
        
        if label != label_predict:
            #now update it
            #CHECK IF RIGHT
            weights += (label*feature)
            bias += label
        
weights       
#bias

array([-61.086591, -42.70582 , -40.30786 ,  -3.146269])

In [13]:
#Now testing perceptron algoirthm

total_err = 0.0
for feature, label in zip(x_test, y_test):
    predict = np.dot(weights, feature) + bias
    label_predict = np.sign(predict)
    
    err = abs(label_predict - label)
    total_err += err
    
    
average_predict_error = total_err / len(x_test)

average_predict_error

0.04

In [21]:
print(f'Weights (Standard): {weights}')
print(f'Average Prediction Error (Standard): {average_predict_error}')

Weights (Standard): [-61.086591 -42.70582  -40.30786   -3.146269]
Average Prediction Error (Standard): 0.04


In [14]:
print(bias)

53.0


# 2b

In [15]:
y_train

array([-1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1,
        1,  1,  1, -1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1,
       -1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,
        1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1,
        1,  1, -1, -1, -1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,
        1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,
        1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1,  1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1,
        1, -1,  1, -1, -1

In [25]:
# now need to do a voted perceptron
# need to initialize variables
vote_w = []
count_list = []
weights = np.zeros(x_train.shape[1])
c = 0
# m is an index
#m = 0
b = 0.0
epochs = 10

In [26]:
# voted perceptron
for T in range(epochs):
    for feature, label in zip(x_train, y_train):
        #prediction = (np.dot(weights, feature) + b) * label
        predict_vote = np.dot(weights, feature) + b
        label_predict_vote = np.sign(predict_vote)
        
        if label_predict_vote != label:
            #update when mistake
            #for voted weights might need c
            # coppy before or after change?
            vote_w.append(weights.copy())
            count_list.append(c)
            
            
            weights += label*feature
            b += label
            #m += 1
            c = 1
    
            
        else:
           
            c = c + 1
            
    

In [27]:
total_vote_err = 0.0
for feature, label in zip(x_test, y_test):
    #what is the point of weight predict
    #weighted_predict = np.dot(feature, weights) + b
    
    #added np.sign
    predicted_vote_label = np.sign(sum(c * np.sign((np.dot(w, feature) + b)) for w, c in zip(vote_w, count_list)))
    #predicted_vote_label = sum(c * np.sign(np.dot(v_w, feature) + b) for v_w, c in zip(vote_w, count_list))
    
    vote_err = abs(predicted_vote_label - label)
    total_vote_err += vote_err
    
average_vote_predict_error = total_vote_err/ len(y_test)

In [28]:
print(f"Average Vote Error: {average_vote_predict_error}")

Average Vote Error: 0.02


In [29]:
for w, c in zip(vote_w, count_list):
    print(f'Count(Vote): {c}, Weight Vector(Vote): {w}' )

Count(Vote): 0, Weight Vector(Vote): [0. 0. 0. 0.]
Count(Vote): 2, Weight Vector(Vote): [ -3.8481 -10.1539   3.8561   4.2228]
Count(Vote): 1, Weight Vector(Vote): [-3.800092 -8.5502   -4.6195    3.46722 ]
Count(Vote): 8, Weight Vector(Vote): [-5.066792 -5.7319   -7.0455    1.58102 ]
Count(Vote): 3, Weight Vector(Vote): [-7.119692 -1.8934   -7.84094   0.36722 ]
Count(Vote): 7, Weight Vector(Vote): [-10.388892 -14.634      7.71636    0.2254  ]
Count(Vote): 5, Weight Vector(Vote): [-14.309292 -10.5617     7.47958   -1.8897  ]
Count(Vote): 9, Weight Vector(Vote): [-17.775992  -6.4893     3.19138   -3.4315  ]
Count(Vote): 10, Weight Vector(Vote): [-17.658162  -4.9104    -4.83862   -3.403469]
Count(Vote): 2, Weight Vector(Vote): [-16.208062  -1.3037    -8.89432   -5.000069]
Count(Vote): 1, Weight Vector(Vote): [-20.884562  -6.9673     2.07468   -5.334559]
Count(Vote): 3, Weight Vector(Vote): [-18.236662 -17.1047     3.40568    0.136141]
Count(Vote): 1, Weight Vector(Vote): [-18.120742 -13.88

In [30]:
wa = np.zeros(x_train.shape[1])
for w in vote_w:
    wa += w
    
wa = wa / len(vote_w)
wa

# if you take the avaerage of all teh vote_weights and then average it, it is nearly the same as teh average perceptron

array([-42.8962813 , -26.81727741, -26.20797595,  -8.54976174])

In [31]:
print(wa)

[-42.8962813  -26.81727741 -26.20797595  -8.54976174]


# 2c

In [21]:
# initialize variables
weights = np.zeros(x_train.shape[1])
epoch = 10
a = np.zeros(x_train.shape[1])
b = 0.0
sum_b = 0.0
iterations = 0


In [22]:
# average Perceptron

for T in range(epoch):
    for feature, label in zip(x_train, y_train):
        predict = np.dot(weights, feature) + b
        predict_label = np.sign(predict)
        
        if predict_label != label:
            weights += feature * label
            b += label
            iterations += 1
            
            a += weights
            sum_b += b

averaged_weights = a / iterations
average_b = sum_b / iterations

In [23]:
# now testing it

total_average_err = 0.0

for feature, label in zip(x_test, y_test):
    prediction = np.dot(averaged_weights, feature) + average_b
    predicted_average_label = np.sign(prediction)
    
    err_av = abs(predicted_average_label - label)
    total_average_err += err_av
    
average_test_err_av = total_average_err / len(y_test)

print(average_test_err_av)

0.036


In [24]:
print(f'Averaged Test Error (average): {average_test_err_av}')
print(f'Average Weight Vector (average): {averaged_weights}')

Averaged Test Error (average): 0.036
Average Weight Vector (average): [-43.13213686 -26.98216475 -26.36360475  -8.5619095 ]


In [32]:
print(averaged_weights)

[-43.13213686 -26.98216475 -26.36360475  -8.5619095 ]


In [34]:
print(f'Average Prediction Error (Standard): {average_predict_error}')
print(f"Average Vote Error: {average_vote_predict_error}")
print(f'Averaged Test Error (average): {average_test_err_av}')

Average Prediction Error (Standard): 0.04
Average Vote Error: 0.02
Averaged Test Error (average): 0.036
